# Generated by Django 4.2.3 on 2023-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mqttdata_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttdata',
            name='vibrations',
            field=models.FloatField(default=0.0),
        ),
    ]
