# Generated by Django 4.2.3 on 2023-09-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_mqttdata_vibrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttdata',
            old_name='vibrations',
            new_name='vibration',
        ),
    ]
