# Generated by Django 4.2.6 on 2023-12-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_vibrationx_mqttdata_vibration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttdata',
            old_name='vibration',
            new_name='vibrationx',
        ),
        migrations.AddField(
            model_name='mqttdata',
            name='vibrationy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mqttdata',
            name='vibrationz',
            field=models.FloatField(default=0.0),
        ),
    ]
