# Generated by Django 4.2.6 on 2023-12-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_vibration_mqttdata_vibrationx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttdata',
            old_name='vibrationx',
            new_name='accelvibX',
        ),
        migrations.RenameField(
            model_name='mqttdata',
            old_name='vibrationy',
            new_name='accelvibY',
        ),
        migrations.RenameField(
            model_name='mqttdata',
            old_name='vibrationz',
            new_name='accelvibZ',
        ),
    ]
