# Generated by Django 4.2.6 on 2023-12-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_rename_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
