# Generated by Django 4.2.3 on 2023-10-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringUpperAndLower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibration_upper', models.IntegerField(default=1000)),
                ('vibration_lower', models.IntegerField(default=0)),
                ('current_upper', models.IntegerField(default=1000)),
                ('current_lower', models.IntegerField(default=0)),
                ('temperature_upper', models.IntegerField(default=1000)),
                ('temperature_lower', models.IntegerField(default=0)),
            ],
        ),
    ]
