# Generated by Django 4.2.3 on 2023-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_monitoringupperandlower_current_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringupperandlower',
            name='current_lower',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoringupperandlower',
            name='current_upper',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='monitoringupperandlower',
            name='temperature_lower',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoringupperandlower',
            name='temperature_upper',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='monitoringupperandlower',
            name='vibration_lower',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoringupperandlower',
            name='vibration_upper',
            field=models.FloatField(default=5),
        ),
    ]
