# Generated by Django 4.2.6 on 2023-12-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_alter_monitoringupperandlower_current_lower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringupperandlower',
            old_name='vibration_lower',
            new_name='cal_vibration_X',
        ),
        migrations.RenameField(
            model_name='monitoringupperandlower',
            old_name='vibration_upper',
            new_name='vibration_X_upper',
        ),
        migrations.AddField(
            model_name='monitoringupperandlower',
            name='cal_vibration_Y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monitoringupperandlower',
            name='cal_vibration_Z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monitoringupperandlower',
            name='vibration_X_lower',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monitoringupperandlower',
            name='vibration_Y_lower',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monitoringupperandlower',
            name='vibration_Y_upper',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='monitoringupperandlower',
            name='vibration_Z_lower',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monitoringupperandlower',
            name='vibration_Z_upper',
            field=models.FloatField(default=5.0),
        ),
    ]
